[workspace]

members = [
    "minecraft-fs", # main binary
    "filesystem",   # fuse filesystem
    "ipc",          # IPC comms shared between fs and test client
    "test-client",  # dummy minecraft client for testing fs
]
