[package]
name = "minecraft-fs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filesystem = { path = "../filesystem" }
ipc = { path = "../ipc" }

env_logger = "0.9"
log = "0.4"
