[package]
name = "test-client"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipc = { path = "../ipc", features = ["client"] }

rand = "0.8"
flatbuffers = "2.0"
env_logger = "0.9"
log = "0.4"
