[package]
name = "mcfuse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filesystem = { path = "../filesystem" }

env_logger = "0.9"
log = "0.4"
